{
 "title": "Doc Pipeline",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Load Generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Generated Documents / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(num_documents_total[5m]))",
     "legendFormat": "docs/sec"
    }
   ]
  },
  { "title": "Data Loading Stage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Prcessed items / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(stage_processed_items_total{stage_name=\"load\"}[5m]))",
     "legendFormat": "total/sec"
    },
    {
     "expr": "sum(rate(stage_errors_total{stage_name=\"load\"}[5m]))",
     "legendFormat": "err/sec"
    }
   ]
  },
  {
   "title": "Processing Latency Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(processing_latency_bucket{stage_name=\"load\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(processing_latency_bucket{stage_name=\"load\"}[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(processing_latency_bucket{stage_name=\"load\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Tokenize Stage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Prcessed items / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(stage_processed_items_total{stage_name=\"tokenize\"}[5m]))",
     "legendFormat": "total/sec"
    },
    {
     "expr": "sum(rate(stage_errors_total{stage_name=\"tokenize\"}[5m]))",
     "legendFormat": "err/sec"
    }
   ]
  },
  {
   "title": "Processing Latency Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(processing_latency_bucket{stage_name=\"tokenize\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(processing_latency_bucket{stage_name=\"tokenize\"}[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(processing_latency_bucket{stage_name=\"tokenize\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Embed Stage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Prcessed items / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(stage_processed_items_total{stage_name=\"embed\"}[5m]))",
     "legendFormat": "total/sec"
    },
    {
     "expr": "sum(rate(stage_errors_total{stage_name=\"embed\"}[5m]))",
     "legendFormat": "err/sec"
    }
   ]
  },
  {
   "title": "Processing Latency Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(processing_latency_bucket{stage_name=\"embed\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(processing_latency_bucket{stage_name=\"embed\"}[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(processing_latency_bucket{stage_name=\"embed\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Index Stage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true
  },
  {
   "title": "Prcessed items / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(rate(stage_processed_items_total{stage_name=\"index\"}[5m]))",
     "legendFormat": "total/sec"
    },
    {
     "expr": "sum(rate(stage_errors_total{stage_name=\"index\"}[5m]))",
     "legendFormat": "err/sec"
    }
   ]
  },
  {
   "title": "Processing Latency Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(processing_latency_bucket{stage_name=\"index\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(processing_latency_bucket{stage_name=\"index\"}[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(processing_latency_bucket{stage_name=\"index\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}